In [61]:
import pandas as pd

In [62]:
df=pd.read_excel("all_data_M_2024.xlsx")

In [63]:
# Convert dataframe from excel to csv
df.to_csv('all_data_M_2024.csv')

In [88]:
# Clean up the read.csv call, having trouble reading the file
# Set ** values to NA
df = pd.read_csv("all_data_M_2024.csv", na_values='**')

/var/folders/y5/lnw79n7s6pxdg8p4fslsq4cc0000gn/T/ipykernel_9438/1598862688.py:3: DtypeWarning: Columns (5,17,31,32) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("all_data_M_2024.csv", na_values='**')

In [89]:
df

,Unnamed: 0,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,O_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC_QUOTIENT,PCT_TOTAL,PCT_RPT,H_MEAN,A_MEAN,MEAN_PRSE,H_PCT10,H_PCT25,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,0,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,total,154187380.0,0.0,NaN,NaN,NaN,NaN,32.66,67920,0.1,14.42,17.66,23.8,37.89,60.44,29990,36730,49500,78810,125720,NaN,NaN
1,1,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,major,10966830.0,0.2,NaN,NaN,NaN,NaN,68.15,141760,0.2,27.41,38.42,58.7,82.5,#,57010,79900,122090,171610,#,NaN,NaN
2,2,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1000,Top Executives,minor,3822780.0,0.3,NaN,NaN,NaN,NaN,67.24,139860,0.4,22.84,33.08,50.48,81.01,#,47510,68800,104990,168490,#,NaN,NaN
3,3,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1010,Chief Executives,broad,211850.0,1.2,NaN,NaN,NaN,NaN,126.41,262930,0.9,35.44,60.61,99.24,#,#,73710,126080,206420,#,#,NaN,NaN
4,4,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,detailed,211850.0,1.2,NaN,NaN,NaN,NaN,126.41,262930,0.9,35.44,60.61,99.24,#,#,73710,126080,206420,#,#,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
409512,409512,4800004,Hill Country Region of Texas nonmetropolitan area,6,TX,0,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,80.0,25.7,0.406,2.48,NaN,NaN,18,37440,9,11.78,14.45,14.95,20.18,24.94,24490,30060,31100,41980,51860,NaN,NaN
409513,409513,5500001,Northwestern Wisconsin nonmetropolitan area,6,WI,0,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,110.0,45.5,2.289,14.01,NaN,NaN,15.66,32570,3,13.99,14.14,14.52,16.3,16.38,29100,29420,30210,33900,34080,NaN,NaN
409514,409514,5500002,Northeastern Wisconsin nonmetropolitan area,6,WI,0,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,260.0,37.8,1.331,8.14,NaN,NaN,15.32,31870,5.6,13.77,13.9,14.04,16.39,16.39,28650,28910,29210,34080,34080,NaN,NaN
409515,409515,5500003,South Central Wisconsin nonmetropolitan area,6,WI,0,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,NaN,NaN,NaN,NaN,NaN,NaN,14.9,31000,4.8,13.68,13.93,14.75,16.25,16.31,28450,28970,30680,33800,33910,NaN,NaN
409516,409516,5500004,Western Wisconsin nonmetropolitan area,6,WI,0,Cross-industry,cross-industry,1235,53-7199,"Material Moving Workers, All Other",detailed,160.0,26.6,1.245,7.62,NaN,NaN,17.23,35830,6.3,13.68,13.94,15.24,16.3,29.66,28450,29000,31700,33910,61690,NaN,NaN

In [90]:
df.dtypes

Unnamed: 0        int64
AREA              int64
AREA_TITLE       object
AREA_TYPE         int64
PRIM_STATE       object
NAICS            object
NAICS_TITLE      object
I_GROUP          object
OWN_CODE          int64
OCC_CODE         object
OCC_TITLE        object
O_GROUP          object
TOT_EMP         float64
EMP_PRSE        float64
JOBS_1000       float64
LOC_QUOTIENT    float64
PCT_TOTAL       float64
PCT_RPT          object
H_MEAN           object
A_MEAN           object
MEAN_PRSE        object
H_PCT10          object
H_PCT25          object
H_MEDIAN         object
H_PCT75          object
H_PCT90          object
A_PCT10          object
A_PCT25          object
A_MEDIAN         object
A_PCT75          object
A_PCT90          object
ANNUAL           object
HOURLY           object
dtype: object

In [91]:
# Isolate to only evaluate national data, not state data
US = df[df['PRIM_STATE']=='US']
# See full display
pd.set_option("display.max_columns", None)

In [92]:
US

,Unnamed: 0,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,O_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC_QUOTIENT,PCT_TOTAL,PCT_RPT,H_MEAN,A_MEAN,MEAN_PRSE,H_PCT10,H_PCT25,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,0,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,total,154187380.0,0.0,NaN,NaN,NaN,NaN,32.66,67920,0.1,14.42,17.66,23.8,37.89,60.44,29990,36730,49500,78810,125720,NaN,NaN
1,1,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,major,10966830.0,0.2,NaN,NaN,NaN,NaN,68.15,141760,0.2,27.41,38.42,58.7,82.5,#,57010,79900,122090,171610,#,NaN,NaN
2,2,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1000,Top Executives,minor,3822780.0,0.3,NaN,NaN,NaN,NaN,67.24,139860,0.4,22.84,33.08,50.48,81.01,#,47510,68800,104990,168490,#,NaN,NaN
3,3,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1010,Chief Executives,broad,211850.0,1.2,NaN,NaN,NaN,NaN,126.41,262930,0.9,35.44,60.61,99.24,#,#,73710,126080,206420,#,#,NaN,NaN
4,4,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,detailed,211850.0,1.2,NaN,NaN,NaN,NaN,126.41,262930,0.9,35.44,60.61,99.24,#,#,73710,126080,206420,#,#,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177819,177819,99,U.S.,1,US,5320A1,"Rental and Leasing Services (5322, 5323, and 5...",4-digit,5,53-7065,Stockers and Order Fillers,detailed,3090.0,12.4,NaN,NaN,0.87,6,19.3,40140,2.1,14.27,16.71,18.26,22,25.56,29680,34770,37970,45760,53170,NaN,NaN
177820,177820,99,U.S.,1,US,5320A1,"Rental and Leasing Services (5322, 5323, and 5...",4-digit,5,53-7070,Pumping Station Operators,broad,500.0,35.6,NaN,NaN,0.14,1,26.24,54580,7.9,18.2,22.78,25.69,29.24,34.37,37850,47390,53440,60820,71480,NaN,NaN
177821,177821,99,U.S.,1,US,5320A1,"Rental and Leasing Services (5322, 5323, and 5...",4-digit,5,53-7072,"Pump Operators, Except Wellhead Pumpers",detailed,500.0,35.6,NaN,NaN,0.14,1,26.24,54580,7.9,18.2,22.78,25.69,29.24,34.37,37850,47390,53440,60820,71480,NaN,NaN
177822,177822,99,U.S.,1,US,5320A1,"Rental and Leasing Services (5322, 5323, and 5...",4-digit,5,53-7190,Miscellaneous Material Moving Workers,broad,NaN,NaN,NaN,NaN,NaN,NaN,19.27,40070,5.2,15.32,17.2,18.14,21.27,23.15,31870,35780,37730,44230,48150,NaN,NaN
177823,177823,99,U.S.,1,US,5320A1,"Rental and Leasing Services (5322, 5323, and 5...",4-digit,5,53-7199,"Material Moving Workers, All Other",detailed,NaN,NaN,NaN,NaN,NaN,NaN,19.27,40070,5.2,15.32,17.2,18.14,21.27,23.15,31870,35780,37730,44230,48150,NaN,NaN

In [98]:
US.sort_values(by="TOT_EMP", ascending=False)

,Unnamed: 0,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,O_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC_QUOTIENT,PCT_TOTAL,PCT_RPT,H_MEAN,A_MEAN,MEAN_PRSE,H_PCT10,H_PCT25,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,0,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,total,154187380.0,0.0,NaN,NaN,NaN,NaN,32.66,67920,0.1,14.42,17.66,23.8,37.89,60.44,29990,36730,49500,78810,125720,NaN,NaN
1,1,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,major,10966830.0,0.2,NaN,NaN,NaN,NaN,68.15,141760,0.2,27.41,38.42,58.7,82.5,#,57010,79900,122090,171610,#,NaN,NaN
2,2,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1000,Top Executives,minor,3822780.0,0.3,NaN,NaN,NaN,NaN,67.24,139860,0.4,22.84,33.08,50.48,81.01,#,47510,68800,104990,168490,#,NaN,NaN
3,3,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1010,Chief Executives,broad,211850.0,1.2,NaN,NaN,NaN,NaN,126.41,262930,0.9,35.44,60.61,99.24,#,#,73710,126080,206420,#,#,NaN,NaN
4,4,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-1011,Chief Executives,detailed,211850.0,1.2,NaN,NaN,NaN,NaN,126.41,262930,0.9,35.44,60.61,99.24,#,#,73710,126080,206420,#,#,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177819,177819,99,U.S.,1,US,5320A1,"Rental and Leasing Services (5322, 5323, and 5...",4-digit,5,53-7065,Stockers and Order Fillers,detailed,3090.0,12.4,NaN,NaN,0.87,6,19.3,40140,2.1,14.27,16.71,18.26,22,25.56,29680,34770,37970,45760,53170,NaN,NaN
177820,177820,99,U.S.,1,US,5320A1,"Rental and Leasing Services (5322, 5323, and 5...",4-digit,5,53-7070,Pumping Station Operators,broad,500.0,35.6,NaN,NaN,0.14,1,26.24,54580,7.9,18.2,22.78,25.69,29.24,34.37,37850,47390,53440,60820,71480,NaN,NaN
177821,177821,99,U.S.,1,US,5320A1,"Rental and Leasing Services (5322, 5323, and 5...",4-digit,5,53-7072,"Pump Operators, Except Wellhead Pumpers",detailed,500.0,35.6,NaN,NaN,0.14,1,26.24,54580,7.9,18.2,22.78,25.69,29.24,34.37,37850,47390,53440,60820,71480,NaN,NaN
177822,177822,99,U.S.,1,US,5320A1,"Rental and Leasing Services (5322, 5323, and 5...",4-digit,5,53-7190,Miscellaneous Material Moving Workers,broad,NaN,NaN,NaN,NaN,NaN,NaN,19.27,40070,5.2,15.32,17.2,18.14,21.27,23.15,31870,35780,37730,44230,48150,NaN,NaN
177823,177823,99,U.S.,1,US,5320A1,"Rental and Leasing Services (5322, 5323, and 5...",4-digit,5,53-7199,"Material Moving Workers, All Other",detailed,NaN,NaN,NaN,NaN,NaN,NaN,19.27,40070,5.2,15.32,17.2,18.14,21.27,23.15,31870,35780,37730,44230,48150,NaN,NaN

In [99]:
pd.set_option("display.max_rows", 100)

In [101]:
US.sort_values(by="TOT_EMP", ascending=False).head(100)

,Unnamed: 0,AREA,AREA_TITLE,AREA_TYPE,PRIM_STATE,NAICS,NAICS_TITLE,I_GROUP,OWN_CODE,OCC_CODE,OCC_TITLE,O_GROUP,TOT_EMP,EMP_PRSE,JOBS_1000,LOC_QUOTIENT,PCT_TOTAL,PCT_RPT,H_MEAN,A_MEAN,MEAN_PRSE,H_PCT10,H_PCT25,H_MEDIAN,H_PCT75,H_PCT90,A_PCT10,A_PCT25,A_MEDIAN,A_PCT75,A_PCT90,ANNUAL,HOURLY
0,0,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,00-0000,All Occupations,total,154187380.0,0.0,NaN,NaN,NaN,NaN,32.66,67920,0.1,14.42,17.66,23.8,37.89,60.44,29990,36730,49500,78810,125720,NaN,NaN
1403,1403,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,00-0000,All Occupations,total,131765830.0,0.0,NaN,NaN,NaN,NaN,32.28,67140,0.1,14.24,17.4,23.05,37.21,60.66,29620,36190,47940,77390,126170,NaN,NaN
12086,12086,99,U.S.,1,US,62,Health Care and Social Assistance,sector,58,00-0000,All Occupations,total,23117850.0,0.0,NaN,NaN,100.00,100,33.56,69800,0.3,15,17.75,23.2,38.69,59.35,31200,36920,48250,80470,123460,NaN,NaN
162181,162181,99,U.S.,1,US,999001,"Federal, State, and Local Government, includin...","cross-industry, ownership",123,00-0000,All Occupations,total,22421560.0,0.0,NaN,NaN,NaN,NaN,34.88,72540,0.1,16.68,22.11,29.84,41.92,59.54,34700,45990,62070,87180,123840,NaN,NaN
834,834,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,43-0000,Office and Administrative Support Occupations,major,18218070.0,0.1,NaN,NaN,NaN,NaN,24.12,50160,0.1,15.29,18.07,22.27,28.24,35.81,31800,37580,46320,58730,74480,NaN,NaN
174631,174631,99,U.S.,1,US,44-45,Retail Trade,sector,5,00-0000,All Occupations,total,15607040.0,0.0,NaN,NaN,100.00,100,21.04,43760,0.1,13.11,14.81,17.41,22.04,30.66,27270,30800,36200,45840,63780,NaN,NaN
2222,2222,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,43-0000,Office and Administrative Support Occupations,major,15152120.0,0.2,NaN,NaN,NaN,NaN,23.81,49530,0.1,15.13,17.9,22,27.73,35.33,31470,37230,45760,57680,73480,NaN,NaN
167977,167977,99,U.S.,1,US,999301,"Local Government, including Schools and Hospit...","cross-industry, ownership",3,00-0000,All Occupations,total,14890280.0,0.0,NaN,NaN,NaN,NaN,31.98,66520,0.2,15.33,20.21,28.6,38.35,51.47,31880,42030,59490,79770,107060,NaN,NaN
13801,13801,99,U.S.,1,US,72,Accommodation and Food Services,sector,57,00-0000,All Occupations,total,14247280.0,0.0,NaN,NaN,100.00,100,18.25,37960,0.3,10.96,13.6,16.56,20.02,27.62,22790,28280,34440,41640,57460,NaN,NaN
111523,111523,99,U.S.,1,US,611000,Educational Services,3-digit,235,00-0000,All Occupations,total,13661980.0,0.0,NaN,NaN,100.00,100,32.55,67700,0.3,15.04,19.94,28.58,38.36,52.63,31290,41480,59440,79800,109470,NaN,NaN
10996,10996,99,U.S.,1,US,61,Educational Services,sector,235,00-0000,All Occupations,total,13661980.0,0.0,NaN,NaN,100.00,100,32.55,67700,0.3,15.04,19.94,28.58,38.36,52.63,31290,41480,59440,79800,109470,NaN,NaN
1312,1312,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,53-0000,Transportation and Material Moving Occupations,major,13645620.0,0.2,NaN,NaN,NaN,NaN,23.44,48750,0.2,14.61,17.17,20.55,25.84,33.95,30390,35710,42740,53750,70620,NaN,NaN
680,680,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,35-0000,Food Preparation and Serving Related Occupations,major,13613490.0,0.2,NaN,NaN,NaN,NaN,17.32,36020,0.4,10.92,13.54,16.41,18.64,23.67,22720,28160,34130,38770,49230,NaN,NaN
791,791,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,41-0000,Sales and Related Occupations,major,13351680.0,0.2,NaN,NaN,NaN,NaN,26,54070,0.3,13.01,14.91,18.01,28.79,47.53,27060,31010,37460,59880,98860,NaN,NaN
2179,2179,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,41-0000,Sales and Related Occupations,major,13268140.0,0.2,NaN,NaN,NaN,NaN,26.01,54110,0.3,13.01,14.91,18.01,28.8,47.58,27060,31000,37460,59890,98970,NaN,NaN
2068,2068,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,35-0000,Food Preparation and Serving Related Occupations,major,13148210.0,0.2,NaN,NaN,NaN,NaN,17.29,35960,0.4,10.91,13.51,16.38,18.57,23.63,22690,28100,34080,38620,49150,NaN,NaN
2696,2696,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,53-0000,Transportation and Material Moving Occupations,major,13015010.0,0.2,NaN,NaN,NaN,NaN,23.24,48350,0.2,14.62,17.13,20.34,25.15,33.19,30400,35640,42300,52310,69040,NaN,NaN
169142,169142,99,U.S.,1,US,31-33,Manufacturing,sector,5,00-0000,All Occupations,total,12767670.0,0.0,NaN,NaN,100.00,100,32.13,66820,0.1,17.01,19.61,24.84,36.78,56.53,35380,40780,51670,76510,117580,NaN,NaN
152013,152013,99,U.S.,1,US,722000,Food Services and Drinking Places,3-digit,5,00-0000,All Occupations,total,12239850.0,0.0,NaN,NaN,100.00,100,17.72,36860,0.4,10.83,13.43,16.35,18.85,26.01,22520,27940,34010,39210,54100,NaN,NaN
14027,14027,99,U.S.,1,US,72,Accommodation and Food Services,sector,57,35-0000,Food Preparation and Serving Related Occupations,major,11294580.0,0.2,NaN,NaN,79.28,93,17.21,35790,0.4,10.83,13.41,16.27,18.43,23.59,22520,27880,33850,38340,49060,NaN,NaN
152974,152974,99,U.S.,1,US,722500,Restaurants and Other Eating Places,4-digit,5,00-0000,All Occupations,total,11045170.0,0.0,NaN,NaN,100.00,100,17.48,36370,0.4,10.79,13.35,16.22,18.51,24.69,22440,27760,33740,38500,51350,NaN,NaN
1,1,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,11-0000,Management Occupations,major,10966830.0,0.2,NaN,NaN,NaN,NaN,68.15,141760,0.2,27.41,38.42,58.7,82.5,#,57010,79900,122090,171610,#,NaN,NaN
152183,152183,99,U.S.,1,US,722000,Food Services and Drinking Places,3-digit,5,35-0000,Food Preparation and Serving Related Occupations,major,10808880.0,0.2,NaN,NaN,88.31,98,17.04,35450,0.4,10.8,13.37,16.2,18.32,23.28,22470,27800,33700,38100,48420,NaN,NaN
7796,7796,99,U.S.,1,US,54,"Professional, Scientific, and Technical Services",sector,5,00-0000,All Occupations,total,10793370.0,0.0,NaN,NaN,100.00,100,50.98,106030,0.4,18.74,26.55,39.93,63.49,93.75,38980,55220,83060,132070,195010,NaN,NaN
93068,93068,99,U.S.,1,US,541000,"Professional, Scientific, and Technical Services",3-digit,5,00-0000,All Occupations,total,10793370.0,0.0,NaN,NaN,100.00,100,50.98,106030,0.4,18.74,26.55,39.93,63.49,93.75,38980,55220,83060,132070,195010,NaN,NaN
74,74,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,13-0000,Business and Financial Operations Occupations,major,10351440.0,0.2,NaN,NaN,NaN,NaN,45.04,93680,0.4,22.75,29.53,38.9,52.58,72.13,47310,61430,80920,109370,150040,NaN,NaN
15400,15400,99,U.S.,1,US,99,"Federal, State, and Local Government, excludin...",sector,123,00-0000,All Occupations,total,10068080.0,0.0,NaN,NaN,100.00,100,37.7,78410,0.1,17.99,23.3,32.16,47.14,63.73,37410,48460,66880,98060,132550,NaN,NaN
161039,161039,99,U.S.,1,US,999000,"Federal, State, and Local Government, excludin...",3-digit,123,00-0000,All Occupations,total,10068080.0,0.0,NaN,NaN,100.00,100,37.7,78410,0.1,17.99,23.3,32.16,47.14,63.73,37410,48460,66880,98060,132550,NaN,NaN
153079,153079,99,U.S.,1,US,722500,Restaurants and Other Eating Places,4-digit,5,35-0000,Food Preparation and Serving Related Occupations,major,9891650.0,0.2,NaN,NaN,89.56,99,16.91,35170,0.4,10.78,13.31,16.08,18.18,23.05,22420,27690,33450,37810,47940,NaN,NaN
1404,1404,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,11-0000,Management Occupations,major,9665840.0,0.2,NaN,NaN,NaN,NaN,69.2,143930,0.3,26.72,37.82,58.93,83.89,#,55580,78660,122580,174490,#,NaN,NaN
508,508,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,29-0000,Healthcare Practitioners and Technical Occupat...,major,9592690.0,0.2,NaN,NaN,NaN,NaN,50.59,105220,0.5,21.13,29.66,39.95,56.92,81.37,43940,61680,83090,118400,169250,NaN,NaN
9824,9824,99,U.S.,1,US,56,Administrative and Support and Waste Managemen...,sector,5,00-0000,All Occupations,total,9260960.0,0.0,NaN,NaN,100.00,100,26.52,55160,0.3,14.45,17,20.36,28.44,45.18,30060,35350,42340,59150,93980,NaN,NaN
349,349,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,25-0000,Educational Instruction and Library Occupations,major,8947710.0,0.1,NaN,NaN,NaN,NaN,31.69,65900,0.5,14.81,19.17,28.47,37.62,50.17,30790,39870,59220,78250,104360,NaN,NaN
115323,115323,99,U.S.,1,US,611100,Elementary and Secondary Schools,4-digit,235,00-0000,All Occupations,total,8824150.0,0.0,NaN,NaN,100.00,100,29.8,61980,0.3,14.7,18.84,27.76,36.88,48.51,30580,39190,57730,76710,100900,NaN,NaN
1473,1473,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,13-0000,Business and Financial Operations Occupations,major,8823120.0,0.2,NaN,NaN,NaN,NaN,45.48,94590,0.4,22.52,29.37,38.8,52.98,74.91,46830,61080,80700,110200,155820,NaN,NaN
103203,103203,99,U.S.,1,US,561000,Administrative and Support Services,3-digit,5,00-0000,All Occupations,total,8758800.0,0.0,NaN,NaN,100.00,100,26.34,54790,0.3,14.39,16.92,19.76,28,45.11,29930,35190,41100,58240,93830,NaN,NaN
1145,1145,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,51-0000,Production Occupations,major,8743450.0,0.2,NaN,NaN,NaN,NaN,24.08,50090,0.1,15.69,17.98,22.09,28.03,36.02,32640,37390,45960,58290,74920,NaN,NaN
126013,126013,99,U.S.,1,US,621000,Ambulatory Health Care Services,3-digit,5,00-0000,All Occupations,total,8644100.0,0.0,NaN,NaN,100.00,100,38.47,80020,0.6,16.03,18.62,25.05,41.5,67.99,33350,38720,52100,86320,141410,NaN,NaN
2529,2529,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,51-0000,Production Occupations,major,8559140.0,0.2,NaN,NaN,NaN,NaN,23.9,49710,0.1,15.64,17.94,22.01,27.8,35.59,32520,37320,45780,57830,74030,NaN,NaN
112614,112614,99,U.S.,1,US,611000,Educational Services,"3-digit, ownership",3,00-0000,All Occupations,total,8320800.0,0.0,NaN,NaN,100.00,100,30.67,63790,0.3,14.78,19.14,28.24,37.38,49.58,30750,39800,58740,77750,103130,NaN,NaN
1901,1901,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,29-0000,Healthcare Practitioners and Technical Occupat...,major,8300380.0,0.2,NaN,NaN,NaN,NaN,50.86,105800,0.5,20.83,29.47,39.91,57.22,81.66,43330,61300,83010,119010,169850,NaN,NaN
4148,4148,99,U.S.,1,US,23,Construction,sector,5,00-0000,All Occupations,total,8127130.0,0.0,NaN,NaN,100.00,100,33.7,70100,0.2,18.04,22.41,29,39.19,54.95,37520,46620,60320,81510,114300,NaN,NaN
111848,111848,99,U.S.,1,US,611000,Educational Services,3-digit,235,25-0000,Educational Instruction and Library Occupations,major,7877950.0,0.1,NaN,NaN,57.66,79,32.8,68210,0.5,15.13,21.87,29.09,38.23,51,31470,45490,60510,79510,106070,NaN,NaN
11321,11321,99,U.S.,1,US,61,Educational Services,sector,235,25-0000,Educational Instruction and Library Occupations,major,7877950.0,0.1,NaN,NaN,57.66,79,32.8,68210,0.5,15.13,21.87,29.09,38.23,51,31470,45490,60510,79510,106070,NaN,NaN
1376,1376,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,53-7000,Material Moving Workers,minor,7871860.0,0.2,NaN,NaN,NaN,NaN,19.76,41100,0.2,14.47,16.69,18.43,22.19,26.6,30100,34720,38340,46150,55320,NaN,NaN
115981,115981,99,U.S.,1,US,611100,Elementary and Secondary Schools,"4-digit, ownership",3,00-0000,All Occupations,total,7771350.0,0.0,NaN,NaN,100.00,100,29.95,62290,0.3,14.64,18.94,28,37.04,48.7,30460,39400,58250,77040,101300,NaN,NaN
2760,2760,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,53-7000,Material Moving Workers,minor,7745490.0,0.2,NaN,NaN,NaN,NaN,19.7,40970,0.2,14.47,16.69,18.41,22.13,26.31,30100,34700,38300,46040,54730,NaN,NaN
796,796,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,41-2000,Retail Sales Workers,minor,7633890.0,0.3,NaN,NaN,NaN,NaN,17.05,35470,0.2,11.62,13.77,16.2,17.83,22.38,24170,28630,33690,37090,46540,NaN,NaN
175053,175053,99,U.S.,1,US,44-45,Retail Trade,sector,5,41-0000,Sales and Related Occupations,major,7594690.0,0.2,NaN,NaN,48.66,88,18.33,38130,0.2,12.3,14,16.63,18.72,26.38,25580,29120,34580,38940,54870,NaN,NaN
2184,2184,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,41-2000,Retail Sales Workers,minor,7573600.0,0.3,NaN,NaN,NaN,NaN,17.04,35440,0.2,11.61,13.76,16.18,17.82,22.35,24150,28620,33660,37070,46490,NaN,NaN
12451,12451,99,U.S.,1,US,62,Health Care and Social Assistance,sector,58,29-0000,Healthcare Practitioners and Technical Occupat...,major,7488690.0,0.2,NaN,NaN,32.39,34,52.85,109920,0.6,22.85,31.29,40.94,57.59,85.03,47520,65080,85150,119790,176850,NaN,NaN
610,610,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,31-0000,Healthcare Support Occupations,major,7448010.0,0.2,NaN,NaN,NaN,NaN,19.06,39650,0.2,13.45,16.05,17.87,21.56,24.99,27980,33380,37180,44850,51980,NaN,NaN
176163,176163,99,U.S.,1,US,48-49,Transportation and Warehousing,sector,59,00-0000,All Occupations,total,7399660.0,0.0,NaN,NaN,100.00,100,30.03,62460,0.2,17.56,20.28,24.36,33.88,44.66,36520,42190,50660,70470,92890,NaN,NaN
75,75,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,13-1000,Business Operations Specialists,minor,7318320.0,0.3,NaN,NaN,NaN,NaN,43.76,91020,0.5,22.45,29.18,38.66,52.05,68.82,46690,60690,80410,108270,143140,NaN,NaN
2000,2000,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,31-0000,Healthcare Support Occupations,major,7135450.0,0.2,NaN,NaN,NaN,NaN,18.93,39380,0.2,13.38,16,17.79,21.39,24.42,27830,33280,37010,44490,50790,NaN,NaN
695,695,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,35-3000,Food and Beverage Serving Workers,minor,7101010.0,0.4,NaN,NaN,NaN,NaN,16.66,34650,0.4,10.52,13,15.13,17.71,23.04,21880,27040,31470,36830,47920,NaN,NaN
2083,2083,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,35-3000,Food and Beverage Serving Workers,minor,6944760.0,0.4,NaN,NaN,NaN,NaN,16.65,34640,0.4,10.51,12.98,15.13,17.67,23.05,21860,27000,31470,36750,47940,NaN,NaN
12552,12552,99,U.S.,1,US,62,Health Care and Social Assistance,sector,58,31-0000,Healthcare Support Occupations,major,6849280.0,0.2,NaN,NaN,29.63,76,18.82,39150,0.2,13.37,16,17.78,21.31,24.08,27810,33280,36980,44320,50090,NaN,NaN
1387,1387,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,53-7060,Laborers and Material Movers,broad,6784150.0,0.2,NaN,NaN,NaN,NaN,19.08,39690,0.2,14.31,16.44,18.07,21.57,24.22,29760,34180,37590,44860,50380,NaN,NaN
2771,2771,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,53-7060,Laborers and Material Movers,broad,6710290.0,0.2,NaN,NaN,NaN,NaN,19.04,39610,0.2,14.31,16.43,18.06,21.53,24.12,29760,34160,37560,44780,50170,NaN,NaN
131670,131670,99,U.S.,1,US,622000,Hospitals,3-digit,235,00-0000,All Occupations,total,6538060.0,0.0,NaN,NaN,100.00,100,41.4,86120,0.1,18.25,22.84,36.64,49.12,65.51,37950,47510,76210,102160,136270,NaN,NaN
162524,162524,99,U.S.,1,US,999001,"Federal, State, and Local Government, includin...","cross-industry, ownership",123,25-0000,Educational Instruction and Library Occupations,major,6476350.0,0.1,NaN,NaN,NaN,NaN,32.58,67760,0.5,15.13,22.19,29.26,38.2,50.42,31470,46150,60850,79460,104880,NaN,NaN
967,967,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,47-0000,Construction and Extraction Occupations,major,6361720.0,0.2,NaN,NaN,NaN,NaN,30.73,63920,0.3,18,22.13,28.06,36.93,48.28,37440,46030,58360,76820,100430,NaN,NaN
175058,175058,99,U.S.,1,US,44-45,Retail Trade,sector,5,41-2000,Retail Sales Workers,minor,6341470.0,0.2,NaN,NaN,40.63,84,16.89,35130,0.2,11.7,13.75,16.08,17.66,21.84,24330,28600,33450,36720,45420,NaN,NaN
509,509,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,29-1000,Healthcare Diagnosing or Treating Practitioners,minor,6338160.0,0.2,NaN,NaN,NaN,NaN,61.8,128550,0.6,31.81,38.54,48.74,64.76,102.34,66160,80170,101370,134700,212870,NaN,NaN
6538,6538,99,U.S.,1,US,52,Finance and Insurance,sector,5,00-0000,All Occupations,total,6239990.0,0.0,NaN,NaN,100.00,100,47.48,98760,0.3,18.55,23.32,35.86,58.31,85.3,38590,48500,74590,121280,177430,NaN,NaN
169910,169910,99,U.S.,1,US,31-33,Manufacturing,sector,5,51-0000,Production Occupations,major,6218770.0,0.1,NaN,NaN,48.71,83,24.31,50570,0.1,16.59,18.49,22.53,28.25,35.44,34510,38450,46870,58760,73710,NaN,NaN
1474,1474,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,13-1000,Business Operations Specialists,minor,6144530.0,0.3,NaN,NaN,NaN,NaN,43.88,91270,0.6,22.11,28.85,38.41,52.01,71.7,45980,60010,79890,108180,149130,NaN,NaN
14041,14041,99,U.S.,1,US,72,Accommodation and Food Services,sector,57,35-3000,Food and Beverage Serving Workers,minor,6079900.0,0.5,NaN,NaN,42.67,86,16.64,34600,0.4,10.45,12.9,15,17.58,23.16,21740,26820,31200,36570,48180,NaN,NaN
4902,4902,99,U.S.,1,US,42,Wholesale Trade,sector,5,00-0000,All Occupations,total,6050580.0,0.0,NaN,NaN,100.00,100,35.66,74170,0.3,17.09,20.55,27.29,39.63,64.28,35560,42750,56770,82420,133700,NaN,NaN
1070,1070,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,49-0000,"Installation, Maintenance, and Repair Occupations",major,6045020.0,0.2,NaN,NaN,NaN,NaN,29.63,61640,0.2,17.4,21.64,27.99,36.11,45.39,36190,45000,58230,75100,94420,NaN,NaN
134279,134279,99,U.S.,1,US,622100,General Medical and Surgical Hospitals,4-digit,235,00-0000,All Occupations,total,5991650.0,0.0,NaN,NaN,100.00,100,41.61,86550,0.1,18.3,22.91,36.84,49.18,65.73,38060,47650,76620,102300,136730,NaN,NaN
2351,2351,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,47-0000,Construction and Extraction Occupations,major,5860770.0,0.3,NaN,NaN,NaN,NaN,30.78,64030,0.3,17.99,22.11,28.04,37,48.48,37420,45990,58330,76960,100830,NaN,NaN
152197,152197,99,U.S.,1,US,722000,Food Services and Drinking Places,3-digit,5,35-3000,Food and Beverage Serving Workers,minor,5855110.0,0.5,NaN,NaN,47.84,92,16.5,34310,0.5,10.45,12.87,15,17.54,22.99,21730,26770,31200,36470,47830,NaN,NaN
115513,115513,99,U.S.,1,US,611100,Elementary and Secondary Schools,4-digit,235,25-0000,Educational Instruction and Library Occupations,major,5764710.0,0.2,NaN,NaN,65.33,98,29.93,62250,0.5,15,21.53,28.61,36.89,47.73,31200,44780,59500,76740,99270,NaN,NaN
166914,166914,99,U.S.,1,US,999300,"Local Government, excluding Schools and Hospit...",4-digit,3,00-0000,All Occupations,total,5672670.0,0.0,NaN,NaN,100.00,100,33.31,69280,0.1,16.65,21.63,29.22,40.08,54.55,34630,44990,60790,83360,113470,NaN,NaN
168298,168298,99,U.S.,1,US,999301,"Local Government, including Schools and Hospit...","cross-industry, ownership",3,25-0000,Educational Instruction and Library Occupations,major,5527600.0,0.2,NaN,NaN,NaN,NaN,31.05,64590,0.5,15,21.84,28.91,37.4,48.72,31200,45420,60130,77790,101330,NaN,NaN
611,611,99,U.S.,1,US,0,Cross-industry,cross-industry,1235,31-1100,Home Health and Personal Care Aides; and Nursi...,minor,5464490.0,0.2,NaN,NaN,NaN,NaN,17.64,36690,0.2,13.01,15.32,17.28,19.21,22.29,27050,31870,35940,39950,46360,NaN,NaN
2454,2454,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,49-0000,"Installation, Maintenance, and Repair Occupations",major,5464460.0,0.3,NaN,NaN,NaN,NaN,29.53,61410,0.2,17.34,21.53,27.83,35.99,45.41,36070,44780,57890,74860,94440,NaN,NaN
1902,1902,99,U.S.,1,US,1,"Cross-industry, Private Ownership only","cross-industry, ownership",5,29-1000,Healthcare Diagnosing or Treating Practitioners,minor,5440330.0,0.3,NaN,NaN,NaN,NaN,62.61,130240,0.6,32.12,38.68,48.81,65,103.25,66810,80450,101530,135200,214750,NaN,NaN
132452,132452,99,U.S.,1,US,622000,Hospitals,"3-digit, ownership",5,00-0000,All Occupations,total,5411880.0,0.0,NaN,NaN,100.00,100,41.61,86550,0.1,18.31,22.92,37.01,49.21,65.22,38080,47670,76990,102350,135660,NaN,NaN
113435,113435,99,U.S.,1,US,611000,Educational Services,"3-digit, ownership",3,25-0000,Educational Instruction and Library Occupations,major,5392850.0,0.2,NaN,NaN,64.81,98,31.2,64890,0.5,15,22,28.97,37.47,48.76,31200,45750,60260,77940,101420,NaN,NaN
153282,153282,99,U.S.,1,US,722511,Full-Service Restaurants,6-digit,5,00-0000,All Occupations,total,5377910.0,0.0,NaN,NaN,100.00,100,18.89,39280,0.5,10.6,13.78,16.98,21.52,29.32,22050,28670,35320,44760,60990,NaN,NaN